server:
  port: 8761

spring:
  application:
    name: server-discovery

eureka:
  client:
    register-with-eureka: false # The server itself is not recorded
    fetch-registry: false       # Does not consult other records
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}","level":"%p","thread":"%t","logger":"%c{1}","message":"%m","application":"${spring.application.name:-}","traceId":"%X{traceId:-}","spanId":"%X{spanId:-}","exception":"%ex"}%n'