services:
  server-gateway:
    container_name: server-gateway
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: server-gateway
    ports:
      - "8090:8090"
    depends_on:
      order-service:
        condition: service_healthy
      server-discovery:
        condition: service_healthy
      jaeger:
        condition: service_started
      keycloak:
        condition: service_healthy
    environment:
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://jaeger:4318/v1/traces
      DISCOVERY_ENDPOINT: http://server-discovery:8761/eureka
      KEYCLOAK_ENDPOINT: http://keycloak:8080/realms
    networks:
      - microservices-net
    restart: unless-stopped

  server-discovery:
    container_name: server-discovery
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: server-discovery
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net
    restart: unless-stopped

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: order-service
    ports:
      - "8082:8082"
    depends_on:
      product-service:
        condition: service_healthy
      server-discovery:
        condition: service_healthy
      jaeger:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://jaeger:4318/v1/traces
      DISCOVERY_ENDPOINT: http://server-discovery:8761/eureka
      KEYCLOAK_ENDPOINT: http://keycloak:8080/realms
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net
    restart: unless-stopped

  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE: product-service
    ports:
      - "8081:8081"
    depends_on:
      server-discovery:
        condition: service_healthy
      jaeger:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      MANAGEMENT_OTLP_TRACING_ENDPOINT: http://jaeger:4318/v1/traces
      DISCOVERY_ENDPOINT: http://server-discovery:8761/eureka
      KEYCLOAK_ENDPOINT: http://keycloak:8080/realms
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.73.0
    container_name: jaeger
    ports:
      - "16686:16686"   # UI Jaeger
      - "4317:4317"     # OTLP gRPC
      - "4318:4318"     # OTLP HTTP
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - microservices-net
    restart: unless-stopped

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    container_name: keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - "8080:8080"
    volumes:
      - ./imports/master-realm.json:/opt/keycloak/data/import/master-realm.json
      - ./imports/demo-ecommerce-realm.json:/opt/keycloak/data/import/demo-ecommerce-realm.json
    command: start-dev --import-realm
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { java.net.URI uri = java.net.URI.create(args[0]); System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)uri.toURL().openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live' ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - microservices-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'ruok' | nc localhost 2181" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - microservices-net
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  microservices-net:
    driver: bridge