spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: ${ORDER_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/order/**

server:
  port: 8090

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% requests
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}