spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/**
              filters:
                - name: RewritePath
                  args:
                    regexp: ^/order/docs/(?<segment>.*)
                    replacement: /docs/${segment}
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/product/**
              filters:
                - name: RewritePath
                  args:
                    regexp: ^/product/docs/(?<segment>.*)
                    replacement: /docs/${segment}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ENDPOINT:http://localhost:8080/realms}/demo-ecommerce

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_ENDPOINT:http://localhost:8761/eureka}

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0   # 100% requests
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG