apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: Jaeger
          matcherRegex: traceID=(\w+)
          name: TraceID
          url: '$${__value.raw}'
          internalLink: true

  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: Loki        # Usa Loki para logs
        spanStartTimeShift: "-1h"  # rango por defecto antes del span
        spanEndTimeShift: "1h"     # rango por defecto después del span
        filterByTraceID: true
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: Prometheus  # Usa Prometheus para métricas
        tags:
          - key: service.name
            value: '${__span.tags.service.name}'