server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [ __meta_docker_container_name ]
        target_label: job
        regex: /(.+)
        replacement: $1
      - source_labels: [ __meta_docker_container_name ]
        target_label: instance
        regex: /(.+)
        replacement: $1
      - source_labels: [ __meta_docker_container_label_com_eureka_app_name ]
        target_label: app
        action: replace
        regex: (.+)
        replacement: $1
    pipeline_stages:
      - json:
          expressions:
            level: level
            message: message
            timestamp: timestamp
            logger: logger
            thread: thread
            traceId: traceId
            spanId: spanId
      - labels:
          level:
          logger:
          thread:
          traceId:
          spanId: